feat: adicionado exercícios de conceito
J0sueTM/lpi4noobs-interactive pull request #1
Opened 2023-09-28 23:46 UTC by grigolin

2023-09-29 00:36 UTC, J0sueTM requested changes
Thanks for the PR.

I found some stuff that could be improved in sake of readability and ease of scripting. I personally think it should be a bit cramped and difficult to write these test statements right now, than having to handle the painstaking errors when actually having to do the live checks themselves.

I'll wait for changes. Thanks in advance!

2023-09-29 00:36 UTC, J0sueTM commented on resources/artifacts/exercises.json
> +        "expects": "passwd `meu_usuario`"
This should be "passwd meu_usuario", the backticks are for the content markdown only

2023-09-29 00:36 UTC, J0sueTM commented on resources/artifacts/exercises.json
> +        "expects": "VAR='Nova variavel'"
Maybe we could check the existence of this variable by a more pragmatic way, like this:

```sh
[[ $VAR == 'Nova variavel' ]] && echo '1' || echo '0'
```

I also think this model of

[[ verification ]] && echo '1' || echo '0'

should become our standard from now on.

2023-09-29 00:36 UTC, J0sueTM commented on resources/artifacts/exercises.json
> +        "expects": "chmod u+x teste.txt"
As stated before, this could be checked by a more pragmatic manner, which wouldn't rely on the user typing exactly `chmod u+x teste.txt`:

```sh
[[ -x teste.txt ]] && echo '1' || echo '0'
```

`-x` is a bash token that means "verify if this file has the execute permission". As stated before, we're using the same pattern for return eitheir '1' or '0'. This should be used on the other expectations as well.

2023-09-29 01:00 UTC, lanjoni commented on resources/artifacts/exercises.json
> +        "expects": "chown novouser teste.txt"
Maybe using the format `chown user:group file` is better, with `stat` to verify who is the owner (you can check `stat --help` for more information).
![image](https://github.com/J0sueTM/lpi4noobs-interactive/assets/91899995/57ee041d-c46e-4e20-8289-48454f92cb91)

2023-09-29 01:04 UTC, lanjoni commented on resources/artifacts/exercises.json
> +        "expects": "chmod o=x teste.txt"
Ok, this point isn't about the verification but about `chmod`. Maybe the user can use another format for the same command because we can use numbers as options to send permissions for `chmod` too. The purpose is: change to `"checks_with_script": true,` and add a simple verification format using `stat`, as I commented above.

Anyway, it will works well, so thanks for the contribution!

2023-09-29 01:06 UTC, lanjoni commented on resources/artifacts/exercises.json
> +        "expects": "chown -R novouser ./novo"
Same [format suggestion](https://github.com/J0sueTM/lpi4noobs-interactive/pull/1/files#r1340780438) to `chown`!

2023-10-02 02:01 UTC, J0sueTM approved these changes
Looks great. Thanks for taking the time and solving the fixes I asked you!

2023-10-02 02:01 UTC, merged